### ISSUE TITLE
Cannot generate native image on Ubuntu 20: "error linking the native image"

### ISSUE THREAD

**Issue by nicokosi** [nicokosi/hubstats#55]
On my Ubuntu machine:

```shell
./generate-executable.sh
```
:scissors: 
```
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libz.a is missing. Please install it.
```
:scissors: 
```
/home/nkosinski/.sdkman/candidates/java/21.0.0.r11-grl/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -ldl -lpthread -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:474)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:441)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:685)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

```shell
git show
commit ab719ae7a8915512d3a8a8e1c47ab00e0e6679cb (HEAD -> master, origin/master, origin/HEAD)
Author: Renovate Bot <bot@renovateapp.com>
Date:   Thu Mar 18 06:22:27 2021 +0000

    Update dependency org.clojure:clojure to v1.10.3
```

```shell
cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

**Comment by nicokosi** [comment]
I found this work-around that worked on my machine (https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz) : 
```sh
sudo apt-get install zlib1g-dev
```
